from __future__ import annotations

import abc
from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class SandboxConfig(BaseModel):
    """Configuration for a sandbox environment."""
    sandbox_type: str = Field(
        default="dynamic-sessions", 
        description="Type of sandbox: dynamic-sessions, container-apps, local-docker"
    )
    packages: List[str] = Field(
        default_factory=list, 
        description="List of pip packages to install"
    )
    timeout_seconds: int = Field(
        default=300, 
        description="Execution timeout in seconds"
    )
    max_memory_mb: int = Field(
        default=1024, 
        description="Maximum memory in MB"
    )
    environment_variables: Dict[str, str] = Field(
        default_factory=dict, 
        description="Environment variables"
    )
    allowed_imports: List[str] = Field(
        default_factory=list, 
        description="Allowed imports for security"
    )


class OutputFile(BaseModel):
    """A file generated by the sandbox execution."""
    name: str
    content_type: str
    size_bytes: int
    download_url: Optional[str] = None
    local_path: Optional[str] = None


class InputFile(BaseModel):
    """A file to be uploaded to the sandbox."""
    name: str
    content: bytes
    content_type: str


class ExecutionResult(BaseModel):
    """Result of code execution in the sandbox."""
    success: bool
    output: str
    error: Optional[str] = None
    files: List[OutputFile] = Field(default_factory=list)
    execution_time_ms: int
    memory_used_mb: Optional[float] = None


class SandboxError(Exception):
    """Base exception for sandbox errors."""
    pass


class SandboxTimeoutError(SandboxError):
    """Exception raised when execution times out."""
    pass


class SandboxResourceError(SandboxError):
    """Exception raised for resource limits (e.g. memory)."""
    pass


class SandboxBackend(abc.ABC):
    """Abstract base class for sandbox backends."""
    
    @property
    @abc.abstractmethod
    def name(self) -> str:
        """Name of the sandbox backend."""
        pass
    
    @abc.abstractmethod
    async def initialize(self, config: SandboxConfig) -> None:
        """Initialize the sandbox with the given configuration."""
        pass
    
    @abc.abstractmethod
    async def execute(self, code: str, files: Optional[List[InputFile]] = None) -> ExecutionResult:
        """Execute Python code in the sandbox."""
        pass
    
    @abc.abstractmethod
    async def install_packages(self, packages: List[str]) -> ExecutionResult:
        """Install additional packages in the sandbox."""
        pass
    
    @abc.abstractmethod
    async def upload_file(self, name: str, content: bytes) -> str:
        """Upload a file to the sandbox. Returns file ID or path."""
        pass
    
    @abc.abstractmethod
    async def download_file(self, file_id: str) -> bytes:
        """Download a file from the sandbox."""
        pass
    
    @abc.abstractmethod
    async def cleanup(self) -> None:
        """Clean up the sandbox resources."""
        pass
    
    @abc.abstractmethod
    async def health_check(self) -> bool:
        """Check if the sandbox backend is healthy."""
        pass
